server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
  servlet:
    session:
      timeout: 5m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingvetdb
    initialization-mode: always
    username: postgres
    password: I3VE6s5upFBvN
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 6
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true