server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
  servlet:
    session:
      timeout: 5m

spring:
  datasource:
    url: jdbc:postgresql://ec2-54-74-35-87.eu-west-1.compute.amazonaws.com:5432/d528531p4p34up
    initialization-mode: always
    username: gszojnmjnlaywp
    password: fed3df9ab1039b5683fca4881adc05e80a5b40aa9f7ff1132d16f1bf66f627d9
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 6
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true