server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
  servlet:
    session:
      timeout: 5m

spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/./home/ubuntu/booking-system-veterinarian-database/database
    username: gszojnmjnlaywp
    password: fed3df9ab1039b5683fca4881adc05e80a5b40aa9f7ff1132d16f1bf66f627d9
    initialization-mode: always
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 6
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

#logging:
#  level:
#    root: DEBUG